general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = pidof hyprlock || (hyprlock & sleep 1)
    after_sleep_cmd = wlr-randr --output eDP-1 --on --scale 1.25 --mode 2880x1800@120.000 --adaptive-sync enabled
}

listener {
    timeout = 60
    on-timeout = brightnessctl -s set 2
    on-resume = brightnessctl -r
}

listener {
    timeout = 120
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 180
    on-timeout = wlr-randr --output eDP-1 --off
    on-resume = wlr-randr --output eDP-1 --on --scale 1.25 --mode 2880x1800@120.000 --adaptive-sync enabled
}

listener {
    timeout = 600
    on-timeout = systemctl suspend
}